In [1]:
# Program to Check whether the following system of homogenous linear equation 
# has non-trivial solution.
# x1 + 2x2 − x3 = 0, 2x1 + x2 + 4x3 = 0, 3x1 + 3x2 + 4x3 = 0.
from sympy import *
A=Matrix([[1,2,-1],[2,1,4],[3,3,4]])
ρA=A.rank()
n=shape(A)
print("The coefficient Matrix A is: ")
display(A)
print(f"Rank of the matrix is {ρA}")
if ρA==n[1]: 
 print("System has trivial solution")
else:
 print("System has non trivial solution")


The coefficient Matrix A is: 


Matrix([
[1, 2, -1],
[2, 1,  4],
[3, 3,  4]])

Rank of the matrix is 3
System has trivial solution


In [2]:
# Program to solve non homogeneous linear system if it is consistent
# x1 + 2 x2 − x3 = 1, 2 x1 + x2 + 4 x3 = 2, 3 x1 + 3 x2 + 4 x3 = 1.
from sympy import *
x,y,z=symbols("x,y,z")
A=Matrix([[1,2,-1],[2,1,4],[3,3,4]])
B=Matrix([[1],[2],[1]])
n=shape(A)
AB=A.col_insert(n[1],B)
ρA=A.rank()
ρAB=AB.rank()
print("The coefficient Matrix A is: ")
display(A)
print("The augmented Matrix AB is: ")
display(AB)
print(f"ρ(A)={ρA} and ρ(AB)={ρAB}")
if ρA==ρAB: 
    if ρA==n[1]:
        print("System has unique solution")
    else:
        print("The system has infinitely many solutions")
    print(solve_linear_system(AB,x,y,z)) 
else:
    print("The system of equations is inconsistent")

The coefficient Matrix A is: 


Matrix([
[1, 2, -1],
[2, 1,  4],
[3, 3,  4]])

The augmented Matrix AB is: 


Matrix([
[1, 2, -1, 1],
[2, 1,  4, 2],
[3, 3,  4, 1]])

ρ(A)=3 and ρ(AB)=3
System has unique solution
{x: 7, y: -4, z: -2}


In [4]:
#Solve the system of equations using Gauss-Seidel method: 
#20 x + y − 2 z = 17; 3 x + 20 y − z = −18; 2 x − 3 y + 20 z = 25.
f1=lambda x,y,z: (17-y+2*z)/20
f2=lambda x,y,z: (-18-3*x+z)/20
f3=lambda x,y,z: (25-2*x+3*y)/20
x0,y0,z0=0,0,0
count=1
e=0.0001 #the tolerable error
print("\nCount\t x\t\t y\t\t z\n")
condition=True
while condition:
    x1=f1(x0,y0,z0)
    y1=f2(x1,y0,z0)
    z1=f3(x1,y1,z0)
    print("%d\t%.5f \t%.5f\t%.5f\n"%(count,x1,y1,z1))
    count=count+1
    e1=abs(x0-x1)
    e2=abs(y0-y1)
    e3=abs(z0-z1)
    x0,y0,z0=x1,y1,z1
    condition = e1>=e and e2>=e and e3>=e
print("\n Solution: x=%0.5f, y=%0.5f and z=%0.5f"%(x1,y1,z1))


Count	 x		 y		 z

1	0.85000 	-1.02750	1.01087

2	1.00246 	-0.99983	0.99978

3	0.99997 	-1.00001	1.00000

4	1.00000 	-1.00000	1.00000


 Solution: x=1.00000, y=-1.00000 and z=1.00000


In [5]:
#Obtain the eigenvalues and eigenvectors for the given matrix.
#A = [[4,3,2],[1,4,1],[3,10,4]]
from numpy import *
A=[[4,3,2],[1,4,1],[3,10,4]]
mat=Matrix(A)
print("The given matrix A is")
display(mat)
eig_val,eig_vec=linalg.eig(array(A))
print("Eigen values: \n",eig_val)
print("Eigen values: \n",eig_vec)

The given matrix A is


Matrix([
[4,  3, 2],
[1,  4, 1],
[3, 10, 4]])

Eigen values: 
 [8.98205672 2.12891771 0.88902557]
Eigen values: 
 [[-0.49247712 -0.82039552 -0.42973429]
 [-0.26523242  0.14250681 -0.14817858]
 [-0.82892584  0.55375355  0.89071407]]


In [6]:
#Compute the numerically largest eigenvalue of following P by power method
# A = [[25,1,2],[1,3,0],[2,0,-4]] take transpose of [1 0 0] as initial 
#approximation to the eigen vector
from numpy import *
A=array([[25,1,2],[1,3,0],[2,0,-4]])
x=array([1,0,0])
λ_i=0
while(True):
    Y=dot(A,x)
    λ=abs(Y).max()
    x=Y/λ
    if abs(λ-λ_i)<0.001:
        break
    else:
        λ_i=λ
        print("\nThe largest Eigenvalue is: %.4f"%λ_i)
        print("\nCorresponding EigenVector is: ",x)
print("\nThe solution is:\n")
print("The largest Eigenvalue is: %.4f"%λ)
print("Corresponding EigenVector is: ",x)



The largest Eigenvalue is: 25.0000

Corresponding EigenVector is:  [1.   0.04 0.08]

The largest Eigenvalue is: 25.2000

Corresponding EigenVector is:  [1.         0.04444444 0.06666667]

The largest Eigenvalue is: 25.1778

Corresponding EigenVector is:  [1.         0.04501324 0.06884378]

The largest Eigenvalue is: 25.1827

Corresponding EigenVector is:  [1.         0.0450722  0.06848451]

The solution is:

The largest Eigenvalue is: 25.1820
Corresponding EigenVector is:  [1.         0.0450804  0.06854337]
